### ISSUE TITLE
[BUG] undefined local variable or method 'subscription' when upgrading to v8

### ISSUE THREAD

**Issue by thiago-sydow** [pay-rails/pay#1084]
## Bug Report

**Describe the Bug:**

Can't retry failed payments for Subscriptions

**To Reproduce:**

 `payment_processor.subscriptions.past_due.each(&:retry_failed_payment)`

When processor is `Pay::Stripe::Subscription`

**Expected Behavior:**

Works as before version 8

**Actual Behavior:**

undefined local variable or method `subscription' for an instance of Pay::Stripe::Subscription

**Environment:**
- Pay gem version: 8.0
- Ruby version: 3.3.4
- Rails version: 7.2
- Operating System: Mac

**Additional Context:**
 
I'm "almost sure" that the issue is that this Line https://github.com/pay-rails/pay/blob/b604d0548874da64d5eb5d5ecff46f63a9751ae5/app/models/pay/stripe/subscription.rb#L335 should call `api_record` instead of `subscription`
 
**Possible Fix:**

Replace `subscription` for `api_record` ? I could not find tests for this method so not sure if it's only that

**Steps to Reproduce with Fix (if available):**

**Related Issues:**

**Labels to Apply:**

**Checklist:**

- [x] I have searched for similar issues and couldn't find any
- [x] I have checked the documentation for relevant information
- [x] I have included all the required information

**Comment by excid3** [comment]
Thanks, released as 8.1.1!
